Sprint 04
k1gabyt0/MovieQuiz pull request #1
Opened 2024-11-24 10:03 UTC by k1gabyt0

![CleanShot 2024-11-24 at 12 52 29](https://github.com/user-attachments/assets/38018f55-5402-4a0a-a2f9-82660aaedd4b)

2024-11-24 10:04 UTC, k1gabyt0 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        noButton.isEnabled = false // дисейблим чтобы нельзя было нажать 100 раз
Чтобы не было такого
![CleanShot 2024-11-24 at 12 17 12](https://github.com/user-attachments/assets/96e2dc4d-7e53-401e-b504-3e6f3f2ae1ab)

2024-11-25 08:15 UTC, Kirchberg requested changes
⚠️ Критические замечания (это нужно исправить обязательно):

1. Необходимо поправить в соответствии с пунктом задания 3.b. скругления постера. В макете есть скругление картинки постера, выставленное в 8, в проекте скругления нет. [[См. скриншот сравнения симулятора и макета](https://ibb.co/chxy9F3)](https://ibb.co/chxy9F3).

Без исправлений этих пунктов, я не смогу принять у тебя работу. Если возникнут вопросы, обязательно задавай их Наставнику!

2024-11-25 08:15 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        noButton.isEnabled = false // дисейблим чтобы нельзя было нажать 100 раз
Молодец, что добавил 🔥

2024-11-25 08:15 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let ok = questions.next()
В твоем коде переменная `ok` используется, чтобы обозначить, закончились ли вопросы или нет. Однако использование имени `ok` может вызвать путаницу, так как неясно, что именно обозначает это название без анализа кода. Было бы полезнее выбрать более конкретное имя, которое чётко описывает её значение и роль.

Вот, например, как можно сделать:
```swift
private func showNextQuestionOrResults() {
    let hasNextQuestion = questions.next()

    if !hasNextQuestion {
        let result = QuizResultViewModel(
            title: "Этот раунд окончен!",
            text: "Ваш результат: \(questions.correctAnswers)/\(questions.count)",
            buttonText: "Сыграть ещё раз"
        )
        show(quiz: result)
    } else {
        show(quiz: convert(model: questions.current))
    }
}
```

2024-11-25 08:15 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            preferredStyle: .alert)
Было бы хорошо привести к одному стилю все инициализатор, как правило делают так:
```swift
let alert = UIAlertController(
    title: result.title,
    message: result.text,
    preferredStyle: .alert
)
```

Такой стиль позволяет легче добавлять новый параметр в конце и не переносить скобку каждый раз для нового параметра

2024-11-25 08:15 UTC, Kirchberg commented on MovieQuiz/Resources/Assets.xcassets/Images/Default.imageset/Default.png
Было бы хорошо удалить этот ресурс, так как он не используется, а приложение будет занимать меньше памяти

2024-11-25 14:05 UTC, k1gabyt0 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let ok = questions.next()
Поправил

2024-11-25 14:05 UTC, k1gabyt0 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            preferredStyle: .alert)
Поправил

2024-11-26 08:15 UTC, Kirchberg approved these changes
Не забудь вмерджить пул-реквест в основную ветку.
Успехов в следующем задании!

2024-11-26 16:16 UTC, merged